[package]
name = "vending-machine"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
async-trait = { workspace = true }
dyn-clone = "1.0.17"
yadir = { workspace = true, features = ["derive"] }
