[package]
name = "infrastructure"
version = "0.1.0"
edition = "2021"

[dependencies]
vending-machine = { path = "../vending-machine" }
sqlx = { version = "0.7.4", features = ["sqlite", "runtime-tokio", "chrono"] }
async-trait = "0.1.81"